/* tslint:disable */
/* eslint-disable */
/**
 * VideoSync API
 * API v2 for VideoSync
 *
 * The version of the OpenAPI document: 2.0
 * Contact: markku.virtanen@flik.fi
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

